"""Create conversation tables

Revision ID: ef1ce0f60850
Revises: 
Create Date: 2026-08-18 11:40:35.368119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef1ce0f60850'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_telegram_user_id'), 'conversations', ['telegram_user_id'], unique=True)
    op.create_table('conversation_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('interest_score', sa.Float(), nullable=False),
    sa.Column('mutuality_score', sa.Float(), nullable=False),
    sa.Column('comfort_score', sa.Float(), nullable=False),
    sa.Column('flirt_score', sa.Float(), nullable=False),
    sa.Column('meeting_readiness', sa.Float(), nullable=False),
    sa.Column('scam_probability', sa.Float(), nullable=False),
    sa.Column('money_focus', sa.Float(), nullable=False),
    sa.Column('manipulation_score', sa.Float(), nullable=False),
    sa.Column('inconsistency_score', sa.Float(), nullable=False),
    sa.Column('pressure_score', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('observations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_assessments_conversation_id'), 'conversation_assessments', ['conversation_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('telegram_message_id', sa.Integer(), nullable=True),
    sa.Column('sender', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_telegram_message_id'), 'messages', ['telegram_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_telegram_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversation_assessments_conversation_id'), table_name='conversation_assessments')
    op.drop_table('conversation_assessments')
    op.drop_index(op.f('ix_conversations_telegram_user_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
